// flow-typed signature: 1e45d36bb71a16e31708cfb5ab55d174
// flow-typed version: <<STUB>>/fela-native_v^5.0.17/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fela-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fela-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fela-native/es/index' {
  declare module.exports: any;
}

declare module 'fela-native/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fela-native/es/index.js' {
  declare module.exports: $Exports<'fela-native/es/index'>;
}
declare module 'fela-native/lib/index.js' {
  declare module.exports: $Exports<'fela-native/lib/index'>;
}
