// flow-typed signature: d7b9adf0553ec49d16c7160510ad6a84
// flow-typed version: <<STUB>>/fela-logger_v^5.0.17/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fela-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fela-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fela-logger/es/index' {
  declare module.exports: any;
}

declare module 'fela-logger/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fela-logger/es/index.js' {
  declare module.exports: $Exports<'fela-logger/es/index'>;
}
declare module 'fela-logger/lib/index.js' {
  declare module.exports: $Exports<'fela-logger/lib/index'>;
}
