// flow-typed signature: 5b4555c1b262e1f0aa84c375453dd571
// flow-typed version: <<STUB>>/fela-plugin-extend_v^6.0.3/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fela-plugin-extend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fela-plugin-extend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fela-plugin-extend/es/index' {
  declare module.exports: any;
}

declare module 'fela-plugin-extend/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fela-plugin-extend/es/index.js' {
  declare module.exports: $Exports<'fela-plugin-extend/es/index'>;
}
declare module 'fela-plugin-extend/lib/index.js' {
  declare module.exports: $Exports<'fela-plugin-extend/lib/index'>;
}
